%% Initial settings

% Calculate Ture # of hetero-dimers and % of total spots
% Then, reduce the spots by homo-dimerization, labelling efficiency, and incidental colocalization

clear; close all;
PixSize = 50; % nm/pix
ImSize = 200; % pix x pix square
DobsG = 0.5; % Apparent total Green spots density (copies / um^2)
DobsR = 0.5; 

FilenameRoot = 'Test_sample_';
kon1 = 0.53; % um^2 / copies / s
koff1 = 8.47; % /s
kon2 = 0.47;
koff2 = 8.00; 
koff3 = 3.86; 
Kd3 = 15; % Kd for hetero-dimer (copies / um^2), 0 for stable dimer, inf for random control

LEr = 70; % Apparent localization error: sigma for single color (include OL error, nm) 
Nframe = 100; % # of frames for one movie
BinWidth = 50; % nm
ColIndexCalcN = [1,2]; % Bin index position for numerator of colocalization index calc
ColIndexCalcD = [9,10]; % denominator, inf for no normalization
NormIndex = [inf,inf]; % denominator, and nomalization factor for histogram, inf for no normalization
GaussFitIndex = 20; % Bin index position for Gauss fitting range 1~
FixYoff = 0; % Fix Y0 as 1 or not for Gauss fitting  
Flip = 0; % Process control Flipped data
Homo = 1; % Homo dimer simulation: 1 or 0
Inci = 1; % Incidental homo dimer simulation: 1 or 0
InciTh = 200; % Threshold distance pf incidental homo dimerization (nm)
EG = 0.7; % Labelling efficiancy for Green: 0~1
ER = 0.7; % 
NumSample = 20;
Iteration = 10;
Comb = 'Test_conditions';


%% Calc
ColSimu_sub_hetero(...
    PixSize, ...
    ImSize, ...
    DobsG, ...
    DobsR, ...
    Kd3, ...
    kon1, ...
    koff1, ...
    kon2, ...
    koff2, ...
    koff3, ...
    LEr, ...
    Nframe, ...
    BinWidth, ...
    ColIndexCalcN, ...
    ColIndexCalcD, ...
    NormIndex, ...
    GaussFitIndex, ...
    FixYoff, ...
    Flip, ...
    Homo, ...
    Inci, ...
    InciTh, ...
    EG, ...
    ER, ...
    NumSample, ...
    Iteration, ...
    FilenameRoot, ...
    Comb, ...
    1);