%% Initial settings

% Calculate Ture # of hetero-dimers and % of total spots
% Then, reduce the spots by homo-dimerization, labelling efficiency, and incidental colocalization

clear; close all;
PixSize = 50; % nm/pix
ImSize = 200; % pix x pix square
Dapp_ALL = 1; % Apparent total (Red + Green) spots density (copies / um^2)

FilenameRoot = 'Test_sample_';
Kd = 10; % copies / um^2, 0 for stable dimer, inf for random control

LEr = 100; % Apparent localization error: sigma for single color (include OL error) 
Nframe = 100; % # of frames for one movie
BinWidth = 50; % nm
ColIndexCalcN = [1,2]; % Bin index position for numerator of colocalization index calc
ColIndexCalcD = [9,10]; % denominator, inf for no normalization
NormIndex = [inf,inf]; % denominator, and nomalization factor for histogram, inf for no normalization
GaussFitIndex = 20; % Bin index position for Gauss fitting range 1~
FixYoff = 1; % Fix Y0 as 1 or not for Gauss fitting  
Flip = 0; % Process control Flipped data
Homo = 1; % Homo dimer simulation: 1 or 0
Inci = 1; % Incidental homo dimer simulation: 1 or 0
InciTh = 200; % Threshold distance pf incidental homo dimerization (nm)
EG = 0.7; % Labelling efficiancy for Green: 0~1   0.74, 0.7
ER = 0.7;
NumSample = 20;
Iteration = 10;


%% Calc
ColSimu_sub(...
    PixSize, ...
    ImSize, ...
    Dapp_ALL, ...
    Kd, ...
    LEr, ...
    Nframe, ...
    BinWidth, ...
    ColIndexCalcN, ...
    ColIndexCalcD, ...
    NormIndex, ...
    GaussFitIndex, ...
    FixYoff, ...
    Flip, ...
    Homo, ...
    Inci, ...
    InciTh, ...
    EG, ...
    ER, ...
    NumSample, ...
    Iteration, ...
    1);